### ISSUE TITLE
couchpotato ebuild

### ISSUE THREAD

**Issue by linux4life1** [soehest/gentoo#7]
first off thanks for the overlay. im not sure if its a bug or a missing dep

but /etc/init.d/couchpotato yields

/etc/default/couchpotato not found using default settings. 
/etc/init.d/couchpotato: line 23: /lib/lsb/init-functions: No such file or directory

**Comment by soehest** [comment]
Sounds odd. I have tried to recreate but have not been able to. Running couchpotato on 3 boxes and none of them exhibits the same behavior. Can you please tell me what exact commands you are issuing to trigger this. Have it always done this, or is it a new problem? And just for good measure what is at line 23 in /etc/init.d/couchpotato? :-)

**Comment by linux4life1** [comment]
line 23 is  " . /lib/lsb/init-functions " 

I try to start it from   "/etc/init.d/couchpotato"

**Comment by soehest** [comment]
Something is wrong with /etc/init.d/couchpotato
It would seem you somehow are using the init included in the couchpotato source code and not the one from the soehest overlay. I have no clue to how they got mixed up, but pretty sure that the ebuild has nothing to do with this :D. Reemerge the package and issue dispatch-conf to get things in working order. Or alternatively remove /etc/init.d/couchpotato and reemerge the package.

**Comment by linux4life1** [comment]
thanks for your help unmerged and re-emerged and I am in CP heaven thank you!
